name: Multi-Environment Image Build and Push

on:
  workflow_dispatch:
  push:
    branches:
     - 'main'


jobs:
    build-and-push-dev:
        runs-on: ubuntu-latest
        environment:
          name: dev

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonsd.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonsd.azurecr.io/sharedservices/librechat:${{ github.sha }}
              docker push creuwbfcommonsd.azurecr.io/sharedservices/librechat:${{ github.sha }}


          - name: Generate Token
            id: create_token
            uses: tibdex/github-app-token@v2
            with:
              app_id: 1295399
              private_key: ${{ secrets.PEM_TO_LIBRE_CHAT_INFRA }}
              installation_retrieval_mode: repository
              installation_retrieval_payload: businessfinland/libre-chat-infra
              revoke: true

          - name: Update CONTAINER_IMAGE_NAME_DEV variable
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
                curl -X PATCH \
                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/CONTAINER_IMAGE_NAME_DEV" \
                -d "{\"value\":\"${{ github.sha }}\"}" \
                || { echo "Failed to update variable"; exit 1; }

          - name: Trigger Deployment Workflow
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
              # Trigger the deployment workflow
                curl -X POST \
                  -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  "https://api.github.com/repos/$TARGET_REPO_NAME/actions/workflows/dev-deploy-infra.yml/dispatches" \
                  -d '{"ref":"main"}'

    build-and-push-test:
        needs : build-and-push-dev
        runs-on: ubuntu-latest
        environment:
          name: test

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonst.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonst.azurecr.io/sharedservices/librechat:${{ github.sha }}
              docker push creuwbfcommonst.azurecr.io/sharedservices/librechat:${{ github.sha }}

          - name: Generate Token
            id: create_token
            uses: tibdex/github-app-token@v2
            with:
              app_id: 1295399
              private_key: ${{ secrets.PEM_TO_LIBRE_CHAT_INFRA }}
              installation_retrieval_mode: repository
              installation_retrieval_payload: businessfinland/libre-chat-infra
              revoke: true

          - name: Update CONTAINER_IMAGE_NAME_TEST variable
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
                curl -X PATCH \
                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/CONTAINER_IMAGE_NAME_TEST" \
                -d "{\"value\":\"${{ github.sha }}\"}" \
                || { echo "Failed to update variable"; exit 1; }

          - name: Trigger Deployment Workflow
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
              # Trigger the deployment workflow
                curl -X POST \
                  -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  "https://api.github.com/repos/$TARGET_REPO_NAME/actions/workflows/test-deploy-infra.yml/dispatches" \
                  -d '{"ref":"main"}'

    build-and-push-prod:
        needs : build-and-push-test
        runs-on: ubuntu-latest
        environment:
          name: prod

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonsp.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonsp.azurecr.io/sharedservices/librechat:${{ github.sha }}
              docker push creuwbfcommonsp.azurecr.io/sharedservices/librechat:${{ github.sha }}


          - name: Generate Token
            id: create_token
            uses: tibdex/github-app-token@v2
            with:
              app_id: 1295399
              private_key: ${{ secrets.PEM_TO_LIBRE_CHAT_INFRA }}
              installation_retrieval_mode: repository
              installation_retrieval_payload: businessfinland/libre-chat-infra
              revoke: true

          - name: Update CONTAINER_IMAGE_NAME_PROD variable
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
                curl -X PATCH \
                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/CONTAINER_IMAGE_NAME_PROD" \
                -d "{\"value\":\"${{ github.sha }}\"}" \
                || { echo "Failed to update variable"; exit 1; }

          - name: Trigger Deployment Workflow
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
            run: |
              # Trigger the deployment workflow
                curl -X POST \
                  -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  "https://api.github.com/repos/$TARGET_REPO_NAME/actions/workflows/prod-deploy-infra.yml/dispatches" \
                  -d '{"ref":"main"}'

 
