name: Multi-Environment Image Build and Push

on:
  workflow_dispatch:
  push:
    branches:
     - 'main'


jobs:
    build-and-push-dev:
        runs-on: ubuntu-latest
        environment:
          name: dev

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonsd.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonsd.azurecr.io/sharedservices/librechat:${{ github.sha }}
              docker push creuwbfcommonsd.azurecr.io/sharedservices/librechat:${{ github.sha }}


    build-and-push-test:
        needs : build-and-push-dev
        runs-on: ubuntu-latest
        environment:
          name: test

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonst.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonst.azurecr.io/sharedservices/librechat:${{ github.sha }}
              docker push creuwbfcommonst.azurecr.io/sharedservices/librechat:${{ github.sha }}

    build-and-push-prod:
        needs : build-and-push-test
        runs-on: ubuntu-latest
        environment:
          name: prod

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonsp.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonsp.azurecr.io/sharedservices/librechat:${{ github.sha }}

